### ISSUE TITLE
Regarding License key for Pganalyze 

### ISSUE THREAD

**Issue by jahnavisana2812** [pganalyze/pganalyze-docs#229]
I'm attempting to set up the enterprise version of pganalyze on our Kubernetes cluster where our PostgreSQL database is running. However, during the installation process, it keeps prompting me for a license key. I believe this key is supposed to be provided by the product team. Can anyone offer assistance with obtaining and applying this license key?

**Comment by lfittl** [comment]
@jahnavisana2812 Please reach out to us using our Contact Us form to get access to an Enterprise Server license key: https://pganalyze.com/contact
